### ISSUE TITLE
icedtea-bin minecraft awt USEFLAG

### ISSUE THREAD

**Issue by InfoPunkie** [gentoo/java-overlay#23]
Could someone please change the minecraft ebuild to support the awt USEFLAG in icedtea-bin 7 and onwards as opposed to the X USEFLAG 6 was using please? Unless this doesn't work, of course.

**Comment by chewi** [comment]
I was aware of that but forgot by the time it got pushed up. I am also surprised that the ebuild still works and that anyone is still using it. Good to know! Minecraft certainly isn't the only Java package needing AWT and what we really need to do is shift these flags into the virtual but it's not quite that simple. For the time being, I will simply point it to the virtual anyway. But not right, now because I'm at work.

**Comment by InfoPunkie** [comment]
@chewi Thank you very much ^^. Yep, I still use it since it's easier than other methods imo. I understand if it's not that simple, so I'll be patient, glad I could make you aware that people are still using it.

**Comment by chewi** [comment]
Fixed in -r5.
