### ISSUE TITLE
dev-java/icedtea wants to "upgrade" from 3.7.0 to 7.2.6.13 AND has a circular dependency on itself

### ISSUE THREAD

**Issue by d4ddi0** [gentoo/java-overlay#44]
idk... is this desire to downgrade a problem with the ebuild, or a core problem with gentoo ebuilds?
If they really cannot handle slot 8...

also the circular dependency:

```diplodocus /root # emerge -1 dev-java/icedtea 
Calculating dependencies... done! 


[ebuild  NS    ] dev-java/icedtea-7.2.6.13:7::java [3.7.0:8::gentoo] USE="alsa cups gtk javascript jbootstrap nsplugin source sunec webstart (-cacao) -cjk -debug -doc -examples -headless-awt (-jamvm) -kerberos -libressl -nss -pax_kernel -pulseaudio -sctp (-selinux) -smartcard {-test} -zero" 49,921 KiB 

Total: 1 package (1 in new slot), Size of downloads: 49,921 KiB 

 * Error: circular dependencies: 

(dev-java/icedtea-7.2.6.13:7/7::java, ebuild scheduled for merge) depends on 
 (dev-java/icedtea-7.2.6.13:7/7::java, ebuild scheduled for merge) (buildtime) 

 * Note that circular dependencies can often be avoided by temporarily 
 * disabling USE flags that trigger optional dependencies. 
```

see also https://forums.gentoo.org/viewtopic-p-8208630.html

**Comment by chewi** [comment]
It's not clear if you want Java 7 or not. Despite the higher version number, 7.2 is for Java 7 while 3.7 is for Java 8. Gentoo does not officially support Java 7 any more and has removed it. It is present in java-overlay because @gnu-andrew still maintains it. Unfortunately Java 7 cannot be built with Java 8 and we don't provide an icedtea-bin for Java 7 any more so you end up with this circular dependency. You can build it with gcj-jdk instead but that is masked along with older gcc versions. Unmask these if that's what you really want to do.

Nothing depends on an unslotted `dev-java/icedtea` so if you don't care about Java 7 then I'm guessing you have this entry in your `@world` file. You should therefore replace it with `dev-java/icedtea:8`.

@gnu-andrew, it's up to you if you want to renumber 7.2 to just 2. There's less of an impact now that it's gone from the main repository but whether it's worth the hassle at this point is debatable.

**Comment by stikonas** [comment]
> Getting rid of the gcj dependency is still something on my todo list, as we do still need a way of bootstrapping with that gone. Gentoo did remove it very prematurely, as gcj is still available in GCC 6, specifically so we have time to work around this.

I have actually managed to bootstrap icedtea without gcj (https://git.stikonas.eu/andrius/openjdk-overlay), although only on some platforms (works on amd64, definitely doesn't work on arm64, presumably works on x86 too...)

**Comment by d4ddi0** [comment]
Closing. No action to take here.
